// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase, getSupabaseBrowserProjectRef } from './client'

function getTokenProjectRef(token: string) {
  try {
    const [, payload] = token.split('.')
    if (!payload) return null
    const decoded = JSON.parse(atob(payload.replace(/-/g, '+').replace(/_/g, '/')))
    const issuer = typeof decoded?.iss === 'string' ? decoded.iss : ''
    return issuer ? new URL(issuer).hostname.split('.')[0] ?? null : null
  } catch {
    return null
  }
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    const currentProjectRef = getSupabaseBrowserProjectRef()

    if (token && currentProjectRef) {
      const tokenProjectRef = getTokenProjectRef(token)
      if (tokenProjectRef && tokenProjectRef !== currentProjectRef) {
        await supabase.auth.signOut({ scope: 'local' })
        return next({ headers: {} })
      }
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
