// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type BrowserSupabaseConfig = {
  url: string;
  publishableKey: string;
};

export function getSupabaseBrowserConfig(): BrowserSupabaseConfig | null {
  const url = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const publishableKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!url || !publishableKey) return null;

  return { url, publishableKey };
}

export function getSupabaseBrowserConfigError(): string {
  const config = getSupabaseBrowserConfig();
  if (config) return '';

  const missing = [
    ...(!import.meta.env.VITE_SUPABASE_URL && !process.env.SUPABASE_URL ? ['SUPABASE_URL'] : []),
    ...(!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY && !process.env.SUPABASE_PUBLISHABLE_KEY
      ? ['SUPABASE_PUBLISHABLE_KEY']
      : []),
  ];
  return `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
}

export function hasSupabaseBrowserConfig() {
  return getSupabaseBrowserConfig() !== null;
}

function createSupabaseClient() {
  const config = getSupabaseBrowserConfig();
  if (!config) {
    const message = getSupabaseBrowserConfigError();
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(config.url, config.publishableKey, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
